### ISSUE TITLE
Issues with this program

### ISSUE THREAD

**Issue by Daniil1288** [lay295/TwitchDownloader#5]
1. Clicking Chat Render straight after launching the program crashes the program. 
2. Links without https:// crash the program due to Uri url = new Uri(text); in ValidateUrl(string text) - if the text is 
  | text | "twitch.tv/videos/1234567890" | string
then the program will crash with Invalid URI: The format of the URI could not be determined UriFormatException.
3. The program doesn't save logs anywhere and doesn't work on my system. First off, it wouldn't even launch on my Win7 system without adding this line:
`   <AppContextSwitchOverrides value="Switch.System.ServiceModel.DisableUsingServicePointManagerSecurityProtocols=false;Switch.System.Net.DontEnableSchUseStrongCrypto=false" /> `
Under `<runtime></runtime>` in App.Config. Probably just my scuffed Windows 7 being scuffed.
Now, about the logs: yeah, there's a window that displays errors but I've been getting NREs after trying to fix this error myself:
"An invalid request URI was provided. The request URI must either be an absolute URI or BaseAddress must be set" 
by adding one / at the end of GetVideoInfo() like this: + "/" (like suggested here if I read it correctly: https://stackoverflow.com/questions/23438416/why-is-httpclient-baseaddress-not-working )
Which appears after trying to download any video/clip/chat at all, and I had absolutely no clue what function even causes it without debugging. 
Turns out, the NRE is caused by string thumbUrl = videoData["data"][0]["thumbnail_url"].ToString().Replace("%{width}", 512.ToString()).Replace("%{height}", 290.ToString()); due to this.videoData being null. 
At this point I have no idea what's wrong after spending a couple of hours debugging since I'm hardly a programmer. Or, well, I did fix that other TwitchChatVideo program not too long ago but that one can't even set gif speeds properly nor crop chat so I'd like to switch to your program if I can get it working. Any help would be appreciated.

**Comment by lay295** [comment]
I'll get a windows 7 machine this weekend and try and reproduce issues 1 and 3. Someone else told me the program crashes when you click chat render but I can't reproduce it on my win10 machine.

**Comment by Daniil1288** [comment]
Turned out that the program didn't work due to FFZ being down at that moment ('Get Info' didn't work), now downloading chat works, but VoDs still can't download even on Win10: 
![image](https://user-images.githubusercontent.com/1404955/68768591-e008e700-0633-11ea-91a2-66e1e3a30df4.png)
Can't render chat either, causes the program to crash but only on Win7:
![image](https://user-images.githubusercontent.com/1404955/68768785-3bd37000-0634-11ea-8d99-6d507f7a263f.png) - caused by System.Windows.Markup.XamlParseException: ""{DependencyProperty.UnsetValue}" is not valid for "DropDownBackground" property." - some sort of an error in ResourceDictionary. Tried to fix it myself, never worked with WPF applications before so I couldn't.
On Win10, it gets to 'Rendering Comments' and then silently closes down without rendering the actual video. (On the Chat Render tab.) Can't debug since I don't have visual studio installed on that system.

Update about the VoD not downloading issue:
Looks like it was due to CultureInfo.InvariantCulture not being set. As such, changing all Windows settings to USA/English fixes this.
During debugging I found out that this line causes the error when i=8 due to my locale being different:
`videoList.Add(new KeyValuePair<string, double>(videoChunks[i + 1], Double.Parse(videoChunks[i].Remove(0, 8).TrimEnd(','))));`
Of course, changing the line to:
`videoList.Add(new KeyValuePair<string, double>(videoChunks[i + 1], Double.Parse(videoChunks[i].Remove(0, 8).TrimEnd(','), CultureInfo.InvariantCulture)));`
Fixes the error.
Still not sure why the program silently quits when trying to render chat on Win10, though.

**Comment by Daniil1288** [comment]
Aaaand about that Win 7 crash:
Fixed!
It was a bug in Xceed.Wpf.Toolkit, fixed it by doing what its creator suggested [here.](https://github.com/xceedsoftware/wpftoolkit/issues/1536#issuecomment-538065029)

Here's another interesting bug I've found that wasn't actually related to FFZ as it turns out.
If the stream's still going and you try downloading the VoD/chat, you are greeted with the error I've reported before:
'An invalid request URI was provided. The request URI must either be an absolute URI or BaseAddress must be set'

**Comment by Daniil1288** [comment]
Couldn't find any more bugs to fix, so here's a feature request. LULW 
Let's say that I only need the first hour of a twelve-hour-long VoD. 
Currently, the VoD would first be downloaded in its entirety and then cropped which wastes quite a bit of time.
On the other hand, [Twitch Leecher](https://github.com/Franiac/TwitchLeecher) would only download the first hour of the VoD. It would be done with the task much quicker.
Any way to make your program do the same, if it doesn't take too much time to rewrite the code?

**Comment by lay295** [comment]
Haha well damn, thanks for looking into a lot of the issues. I'll be sure to implement them in the next release for others :)

Also my program should be only downloading the first hour of the VOD too. I just tried it on one and it didn't download any extra needed parts. Are you not finding that to be the case?

**Comment by lay295** [comment]
Well anyways I put a release up with your fixes. Let me know if anything still isn't working or open another issue if you find something else.

**Comment by Daniil1288** [comment]
Everything's almost good now except for this:
Still having issues while downloading chat (BaseAddress, unable to get clip/video info) - fixed in my build though;
Error.txt does not seem to appear after an error pops up so I don't have any logs to send this time around either;
Settings do not save after changing them (for example, I'd like my videos to be 400 in width by 1080 in height; if I were to close the program after setting them, the settings would reset to default ones since there's no config.json file or anything like that)

**Comment by Daniil1288** [comment]
Also, if there's any way to speed up the rendering of chat, let me know, please. It takes a good hour to render 2 and a half hours of chat.
By the way, for some reason another program using the same libs as yours renders chat faster by a small margin; maybe due to the 'rendering comments' phase taking a bit of time. Still, it took it a minute less to download and then render 2h49mins of chat whereas your program only had to render 2h22mins. 
I'd also like to suggest an option for the chat to automatically start rendering after the logs have finished downloading. Would save some time, too.

**Comment by Daniil1288** [comment]
Also, if it is a possibility to somehow add an option to re-encode the downloaded VoD into CFR from VFR by using ffmpeg (since VFR audio still causes audio sync issues in pretty much any NLE, notably Adobe Premiere which I happen to use), it would be very welcome. 
As such, it's been a problem with the program I used to use which had many users report it over here: https://github.com/Franiac/TwitchLeecher/issues?utf8=%E2%9C%93&q=audio+sync
For example, the VoD I downloaded today happened to have the issue of its audio being 1000 ms behind video. Fixing it isn't that trivial if you notice the issue after having edited half the video already.
More on the issue here in case you need more info: https://community.adobe.com/t5/premiere-pro/audio-out-of-sync-after-importing/m-p/4531895

**Comment by Daniil1288** [comment]
@lay295, should I open another issue for this?

**Comment by Daniil1288** [comment]
Also, attempting to run a second instance of a program (one to download a VoD, the other to render chat) causes weird things to occur: closing down one instance crashes the other, for example.

**Comment by lay295** [comment]
I'll just reopen the issue. To be honest man the VOD downloader was mainly an afterthought and the main part was the chat render. I'm not too knowledgeable about ffmpeg, but I can try and fix the desync issue. 

I only had the idea that one program would be open at a time, so there's probably some IO conflicts when multiple are open.

Also there is probably a way to significantly speed up chat rendering by editing the library I'm using to use NVENC if you have an nvidia gpu as I have in #8 . The program is not too optimized as it's thrown together.

It's near the end of the semester for me and I only really have time to work on this on weekends, i'll look into the issues when I can.

**Comment by goldbattle** [comment]
Closing due to old age, feel free to reopen if this is still an issue with the current release.
